Repository rommapp/romm, pull requests merged in 2023-10, with the labels that each got.

#409 [ROMM-408] Fix reset store on navigate
  frontend/src/stores/roms.js
  frontend/src/views/Gallery/Base.vue
Labels: bug

#372 Updated readme with up-to-date info
  .github/resources/discord_banner.png
  .github/resources/romm.png
  .github/resources/romm.svg
  .github/resources/screenshots/details.png
  .github/resources/screenshots/gallery.png
  .github/resources/screenshots/home.png
  .github/resources/screenshots/m_details.png
  .github/resources/screenshots/m_gallery.png
  .github/resources/screenshots/m_home.png
  .github/resources/screenshots/m_search.png
  .github/resources/screenshots/search.png
  .github/resources/wiki_banner.png
  README.md
  unraid_template/romm.xml
Labels: documentation

#357 Scheduled tasks
  .gitignore
  backend/config/__init__.py
  backend/endpoints/scan.py
  backend/endpoints/tests/test_heartbeat.py
  backend/handler/fixtures/ps2_opl_index.json
  backend/handler/igdb_handler.py
  backend/handler/tests/cassettes/test_switch_titleid_rom.yaml
  backend/handler/tests/test_igdb_handler.py
  backend/logger/logger.py
  backend/main.py
  backend/scheduler.py
  backend/tasks/__init__.py
  backend/tasks/exceptions.py
  backend/tasks/scan_library.py
  backend/tasks/update_mame_xml.py
  backend/tasks/update_switch_titledb.py
  backend/tasks/utils.py
  backend/utils/cache.py
  backend/utils/fastapi.py
  backend/utils/redis.py
  backend/utils/socket.py
  backend/utils/tests/test_fastapi.py
  backend/watcher.py
  backend/worker.py
  docker/init_scripts/init
  docker/init_scripts/init_scheduler
  docker/init_scripts/init_watchdog
  docker/init_scripts/init_worker
  env.template
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/Drawer/Footer.vue
  frontend/src/plugins/vuetify.js
  frontend/src/styles/scrollbar.css
  frontend/src/styles/themes.js
  frontend/src/views/Settings/ControlPanel.vue
  frontend/src/views/Settings/General/Settings.vue
  frontend/src/views/Settings/General/ThemeOption.vue
  frontend/src/views/Settings/UserInterface/Theme.vue
  frontend/src/views/Settings/Users/Users.vue
  poetry.lock
  pyproject.toml
  pytest.ini
Labels: feature

#420 Fix nginx max body size
  docker/init_scripts/init_scheduler
  docker/init_scripts/init_watchdog
  docker/nginx/default.conf
  poetry.lock
Labels: bug
