Repository rommapp/romm, pull requests merged in 2023-11, with the labels that each got.

#436 Frontend refactor
  backend/endpoints/tests/test_heartbeat.py
  backend/main.py
  frontend/src/components/Dashboard/Platforms.vue
  frontend/src/components/Dashboard/Recent.vue
  frontend/src/components/Dashboard/Summary.vue
  frontend/src/components/Details/ActionBar.vue
  frontend/src/components/Details/BackgroundHeader.vue
  frontend/src/components/Details/Cover.vue
  frontend/src/components/Details/Info.vue
  frontend/src/components/Details/ScreenshotsCarousel.vue
  frontend/src/components/Details/Title.vue
  frontend/src/components/Dialog/Rom/SearchRom.vue
  frontend/src/components/Gallery/AppBar/Base.vue
  frontend/src/components/Gallery/AppBar/FilterBar.vue
  frontend/src/components/Gallery/AppBar/GalleryViewBtn.vue
  frontend/src/components/Gallery/AppBar/ScanBtn.vue
  frontend/src/components/Gallery/AppBar/UploadRomBtn.vue
  frontend/src/components/Gallery/FabMenu/Base.vue
  frontend/src/components/Game/Card/Cover.vue
  frontend/src/components/Platform/PlatformCard.vue
  frontend/src/components/Platform/PlatformIcon.vue
  frontend/src/components/Platform/PlatformListItem.vue
  frontend/src/components/Settings/General/TaskStatus/TaskScheduler.vue
  frontend/src/components/Settings/General/TaskStatus/TaskStatusCard.vue
  frontend/src/components/Settings/General/TaskStatus/TaskWatcher.vue
  frontend/src/components/Settings/General/Theme/ThemeCard.vue
  frontend/src/components/Settings/General/Theme/ThemeOption.vue
  frontend/src/plugins/router.js
  frontend/src/stores/download.js
  frontend/src/styles/themes.js
  frontend/src/utils/utils.js
  frontend/src/views/Dashboard/Base.vue
  frontend/src/views/Details/Base.vue
  frontend/src/views/Gallery/Base.vue
  frontend/src/views/Library/Scan/Base.vue
  frontend/src/views/Settings/ControlPanel/Base.vue
  frontend/src/views/Settings/ControlPanel/General/Base.vue
  frontend/src/views/Settings/ControlPanel/Users/Base.vue
  frontend/src/views/Settings/General/Settings.vue
Labels: refactor, improved performance

#442 Cover size standarization
  backend/config/__init__.py
  backend/handler/igdb_handler.py
  backend/handler/tests/test_igdb_handler.py
  backend/utils/fs.py
  backend/utils/tests/test_fs.py
  frontend/src/components/Details/Cover.vue
  frontend/src/components/Dialog/Rom/SearchRom.vue
  frontend/src/components/Game/Card/Cover.vue
  frontend/src/views/Details/Base.vue
  poetry.lock
  pyproject.toml
Labels: ui/ux

#365 Models and API refactor
  backend/alembic/env.py
  backend/alembic/versions/0009_models_refactor.py
  backend/alembic/versions/0010_igdb_id_integerr.py
  backend/alembic/versions/0011_drop_has_cover.py
  backend/endpoints/identity.py
  backend/endpoints/oauth.py
  backend/endpoints/platform.py
  backend/endpoints/rom.py
  backend/endpoints/scan.py
  backend/endpoints/search.py
  backend/endpoints/tests/test_rom.py
  backend/handler/db_handler.py
  backend/handler/igdb_handler.py
  backend/handler/tests/conftest.py
  backend/handler/tests/test_db_handler.py
  backend/handler/tests/test_igdb_handler.py
  backend/main.py
  backend/models/platform.py
  backend/models/rom.py
  backend/models/tests/test_rom.py
  backend/utils/fastapi.py
  backend/utils/fs.py
  backend/utils/tests/test_fastapi.py
  backend/utils/tests/test_fs.py
  frontend/src/components/Details/ActionBar.vue
  frontend/src/components/Details/Info.vue
  frontend/src/components/Details/Title.vue
  frontend/src/components/Dialog/Rom/DeleteRom.vue
  frontend/src/components/Dialog/Rom/EditRom.vue
  frontend/src/components/Dialog/Rom/SearchRom.vue
  frontend/src/components/Dialog/Rom/UploadRom.vue
  frontend/src/components/Dialog/User/CreateUser.vue
  frontend/src/components/Dialog/User/DeleteUser.vue
  frontend/src/components/Dialog/User/EditUser.vue
  frontend/src/components/Gallery/FabMenu/Base.vue
  frontend/src/components/Game/Card/ActionBar.vue
  frontend/src/components/Game/Card/Cover.vue
  frontend/src/components/Game/DataTable/Base.vue
  frontend/src/components/Platform/PlatformCard.vue
  frontend/src/components/Platform/PlatformListItem.vue
  frontend/src/services/api.js
  frontend/src/stores/platforms.js
  frontend/src/views/Details/Base.vue
  frontend/src/views/Gallery/Base.vue
  frontend/src/views/Home.vue
  frontend/src/views/Library/Scan/Base.vue
  frontend/src/views/Settings/ControlPanel/Users/Base.vue
  poetry.lock
  pyproject.toml
Labels: refactor

#452 [ROMM-450][ROMM-449] Improve rom sort order
  backend/endpoints/rom.py
  backend/handler/db_handler.py
  backend/models/rom.py
  frontend/src/plugins/vuetify.js
  frontend/src/stores/roms.js
Labels: ui/ux

#463 Nginx logformat touchup
  docker/nginx/default.conf
Labels: other
